### ISSUE TITLE
TC_11.002.01.001 | [Teacher ] Header > "Профиль" button > Visibility check

### ISSUE THREAD

**Issue by matveyvolodin** [RedRoverSchool/BookClubQA_Python_2024_fall#131]
[US_11.002.001 | [Teacher ] Header > "Профиль" button > Visibility, Clickability, Redirect #38](https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/38)

Description:

Verify the visibility of the "Профиль" button on all pages logged as a teacher.

Preconditions:

1. The user must be logged in as a teacher.
2. The site has the next pages:
- Main page: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/
- "Найти репетитора" page : http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/list/
- "Регистрация" page:  http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/signup/
- "Создать объявление" page: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/create/
-  "Профиль" page: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/profile/
-  "Cтатистика" page: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/statistics/

Steps:

1.  Open the Main page: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/
2.  Verify the visibility of the "Профиль" button in the header
3.  Repeat steps from 1 to 2 for every site page, using parametrization.

Expected results:

1. The "Профиль" button is visible on every site page

**Comment by matveyvolodin** [comment]
https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/38

**Comment by matveyvolodin** [comment]
I would like to request a TC review. Is it necessary to divide this TC into several ones to test button visibility, hover and redirect separately. Is the TC correctly designed considering parameterization?

**Comment by KatyaMy** [comment]
> I would like to request a TC review. Is it necessary to divide this TC into several ones to test button visibility, hover and redirecttion separately. Is the TC correctly designed considering parameterization?

it looks good for me 😊

**Comment by matveyvolodin** [comment]
Merged to main
