### ISSUE TITLE
US_17.003.001 | Student workspace for teacher > With adding lesson(s) > A lessons section for my students

### ISSUE THREAD

**Issue by OlhaVatsyk** [RedRoverSchool/BookClubQA_Python_2024_fall#138]
Description:
As a teacher, I want to view the adding lessons section to display up-to-date information about the lessons added for my students so I can easily keep track of what lessons have been added.

Precondition:
1. The user must be registered as a teacher and login
2. Having at least one confirmed student

Acceptance Criteria:
1. The button "Добавить урок" is displayed on the page.
2. The workspace displays the following messages when no lessons or resources have been added:
   "Уроки пока не добавлены."
3. The button "Добавить урок" redirects to its respective functionality when clicked.

**Comment by konsaf** [comment]
I approve.
