### ISSUE TITLE
US_05.001.006 | Find a Teacher > Filter Search (Teacher) > Filter Teacher [min_price] | check the "Фильтровать" button and rezult with 0 in min field

### ISSUE THREAD

**Issue by AlexSrgv** [RedRoverSchool/BookClubQA_Python_2024_fall#243]
Precondition:
unauthorized user on the home page

Steps:
1. click on the "Найти репититора" button
2. verifying   0 in the minimal prize field 
3. verifying availability of "Фильтровать" button 
4. click on the  "Фильтровать" button 
5. verifying the result

Expected result:
1. "Найти репититора" button and "Фильтровать" button  should be visible
2. after search should be visible all the teachers pages

**Comment by OxanaSum** [comment]
1) Насколько я понимаю, у вас не US, а TC. Тогда название вашей задачи должно начинаться с литер TC:
например, 
**ТС**_05.001.006...

2) У TC внутри US своя нумерация, например, ТС_05.001.006.**002**...

Те итого я бы переименовала:
ТС_05.001.006.002 | Find a Teacher > Filter Search (Teacher) > Filter Teacher [min_price] | check the "Фильтровать" button and rezult with 0 in min field

**Comment by OxanaSum** [comment]
Упоминаем cозданый тест-кейс полностью (как несколькими строками выше), чтоб было видно, что сделано, что нет, и какова текущая нумерация тест-кейсов в этой US:
![изображение](https://github.com/user-attachments/assets/098bba8b-4733-425e-9d39-2fd2dd78acfd)

**Comment by OxanaSum** [comment]
И еще по содержанию тест-кейса, 5ый шаг, на мой взгляд, лишний - не требует действий от тестировщика.  А мы итак идем смотреть как фактический результат соотносится с ожидаемым.

**Comment by AlexSrgv** [comment]
Окей, по возможности все исправлю.
Спасибо!
Просто не привычно работать с дашбордом гитхаба))
