### ISSUE TITLE
TC_13.001.004 | [Teacher]My_announcement > Verify the ability to see detailed ad statistics

### ISSUE THREAD

**Issue by matveyvolodin** [RedRoverSchool/BookClubQA_Python_2024_fall#293]
Description:
Verify that the view counter is displayed on the announcement page.

Preconditions:

1. User is logged in as a Teacher
2. Teacher has at least one pre-published announcement

Steps:

1. Open the announcement page: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/listings/my_listing/

Expected results:

The view counter "Общее количество просмотров" is displayed on the announcement page.

[US_13.001 | [Teacher]My_announcement > Contents of the 'Мое объявление' page](https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/26)

**Comment by KatyaMy** [comment]
@matveyvolodin **12.26.2024 >UPD: Вид статитики поменялся теперь это просто счетчик просмотровх (Общее количество просмотров: 49)**

**Comment by matveyvolodin** [comment]
@KatyaMy Исправил TC на проверку наличия счетчика просмотров, АТ в репозитории соответствует обновленному TC.

**Comment by matveyvolodin** [comment]
Merged to main
