### ISSUE TITLE
TC_13.001.005 | [Teacher]My_announcement > Verify the ability to hide the ad from students

### ISSUE THREAD

**Issue by matveyvolodin** [RedRoverSchool/BookClubQA_Python_2024_fall#294]
[US_13.001 | [Teacher]My_announcement > Contents of the 'Мое объявление' page](https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/26)

Description:
Verify the ability to hide the ad from students after clicking the "Сделать объявление невидимым для учеников" button.

Preconditions:

1. User is logged in as a Teacher
2. Teacher has at least one prepublished announcement

Steps:

1. Open the anouncement page: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/listings/my_listing/
2. Click the  "Сделать объявление невидимым для учеников"  button

Expected results:

1. The message "Теперь обьявление недоступно" is displayed
2. The ad is no longer visible to students

**Comment by SimonGertz** [comment]
А это не должно принадлежать этой стори https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/36 ?

**Comment by matveyvolodin** [comment]
@SimonGertz  @KatyaMy Видимо должно, мне кажется тут продублирован критерий приемки в двух разных US, наверное нужно закрыть мой TC как дубль и исправить  US [https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/26](https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/26) чтоб не было дублирования тестового покрытия.
