### ISSUE TITLE
TC_13.001.006 | Header-Teacher > My announcements ("Мои объявления") when User has an announcement > Verify the category is correct in the announcement

### ISSUE THREAD

**Issue by SimonGertz** [RedRoverSchool/BookClubQA_Python_2024_fall#329]
https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/26
**Description:**

Verify the teacher able to hide the announcement from the list of announcements.

**Preconditions:**

User have a registered Teacher's account
Teacher is logged in
User is on the page My announcements ("Мои объявления")
Teacher has at least one announcement

**Steps:**

Navigate to 'Мое объявление'
Verify the category matches the entered one

**Expected results:**

The names match

**Comment by matveyvolodin** [comment]
What exactly does this test check? Is it hiding the announcement or matching the names?
