### ISSUE TITLE
TC_15.001.002 | Header - Teacher > "Вoйти" - button is available when user isn't logged in

### ISSUE THREAD

**Issue by VolhaDev** [RedRoverSchool/BookClubQA_Python_2024_fall#352]
https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/13 

**Description**: Verify that the "Войти" button is present and enabled in the header when a user is not logged in.

**Preconditions:**
1. User is not logged in.
2. Main page is opened.

**Steps:**
1. Navigate to the main page of the website.
2. Locate the header section of the page.
3. Verify the presence of the "Войти" button in the header.
4. Verify that the "Войти" button is enabled (clickable).

**Expected results:**
1. The "Войти" button should be visible in the header section of the main page.
2. The "Войти" button should be enabled, allowing the user to click on it.

**Comment by KatyaMy** [comment]
Мне какжется это дубль
