### ISSUE TITLE
TC_00.003.003.002 | Main page(body) - All users > Verify clicking bottom More button takes user to the Telegram channel for tutors

### ISSUE THREAD

**Issue by usergalina1** [RedRoverSchool/BookClubQA_Python_2024_fall#46]
**Description:**
Verify clicking More button takes user to the Telegram channel for tutors

**Steps:**

1. Open the site: http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/
2. Click bottom "Подробнее"button
3. Verify the Telegram channel for students opens

**Expected result:**
The user is being redirected to the https://t.me/misleplav_tutors/11

**Comment by usergalina1** [comment]
> 1. Третий шаг лишний
> 
Не согласна. 
Т.к. по правилам написания ТК нужно уточнять, что точно мы проверяем.   Название теста должно отражаться в последнем шаге. 

> 3. Тут лучше конкретизировать, где именно находится данная кнопка "Подробнее"
> 
Step 2. Click bottom "Подробнее"button.   (в переводе: Клик **нижнюю** "Подробнее" кнопку)


> 4. В заголовке заменить More на "Подробнее" (в кавычках)
Исправила.

**Comment by tereshenkov29** [comment]
> Третий шаг лишний
> Не согласна.
> Т.к. по правилам написания ТК нужно уточнять, что точно мы проверяем. Название теста должно отражаться в последнем шаге.

сам тест проверяет то, что написано в 3-м шаге
суть теста - пройти по шагам и получить результат
шаги - это просто набор действий, которые нужно выполнить, чтобы получить результат - нажать, ввести, удалить и т.п.
нажали на кнопку - результат нажатия это открытие страницы - и это подтверждает проверку по тесту
поэтому шаг "проверить, что страница открылась" - избыточный

**Comment by tereshenkov29** [comment]
> Тут лучше конкретизировать, где именно находится данная кнопка "Подробнее"
> Step 2. Click bottom "Подробнее"button. (в переводе: Клик нижнюю "Подробнее" кнопку)

нижняя - это какая? а если страницу поменяют, и кнопка перестанет быть нижней? лучше привязываться к каким-то элементам на странице ("В Хедере", "Под заголовком" и т.п.)

**Comment by usergalina1** [comment]
I changed the Step 3
from "Verify the Telegram channel for tutors opens" to "Observe the Telegram channel for tutors opens"


Maybe, it's better here.
