### ISSUE TITLE
[DEPRECATED] == US_12.001| [Teacher] Create announcement  >  Create teacher announcement

### ISSUE THREAD

**Issue by KatyaMy** [RedRoverSchool/BookClubQA_Python_2024_fall#5]
****_As a teacher,_** I want to create an advertisement by filling out a form with information about myself, my services, and contact details so potential students can find and contact me for lessons.**

**Precondition:** 
1. The user must be **Registered as a teacher**
2. The user must be signed in.
3. The page "[Создать объявление](https://misleplav.ru/create/)" is opened

**Acceptance criteria:**

1. The teacher can fill out a form with the following details about their services: 

**(Required fields:)**
 - Name: Fields for Last Name, First Name, and Middle Name.
 - About Myself: A text box where teachers can describe themselves.
 - Your photo: Recommended size: 400x300.
Supported file formats for profile pictures should include common formats like JPEG (JPG) and PNG for compatibility and quality.
 - Subjects: Dropdown menu to select the subject(s) you teach.
 - If a category is missing, there’s an option to contact support.
 - Teaching Experience: Field to enter teaching experience (in years, numbers only).

 - Lesson Cost: Field to enter lesson cost (numbers only).
 - Lesson Duration: Field to specify lesson duration (numbers only).
 
 **(Optional fields:)**

Specialized Education: 
- A checkbox will be used to indicate if the teacher has specialized education.
- Free First Lesson: Checkbox will offer a free first lesson.

2. The teacher can add contact information using the "Добавить еще один контакт" button.
3. The teacher can choose the communication method (for example, WhatsApp, Telegram, Skype).~~
4. (**Required fields:**) The teacher can enter a phone number or username, depending on the method selected. 
5. The teacher can add and delete an unlimited number of contacts. 
6. The teacher can save the announcement.
7. Once saved, the announcement becomes visible on the page [Найти репетитора](http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/listings/list/)

8. A "Назад" button is available on the form.
9. The "Назад" button takes the teacher to the menu with all announcements.
10. Changes in the form are not saved when the tutor clicks "Назад."

**Comment by Cruz06** [comment]
I think it is OK. Just one observation: may be in field "Your photo" should be specified type of file?

**Comment by KatyaMy** [comment]
there is nothing like that

**Comment by konsaf** [comment]
It looks pretty good.

**Comment by tgusachenko** [comment]
Я еще подумала про обязательность/необязательность полей. Думаю стоит указать, что произойдет, если не заполнить обязательные поля (например, выводится сообщение об ошибке). Но сейчас на сайте нет обозначения типа * для обязательных полей, мы не видим какие поля обязательные, а какие нет. Может это надо уточнить у Виктора

**Comment by tgusachenko** [comment]
[TC_12.001.001 | [Teacher] Create announcement > Create teacher announcement > Verify the announcement is created after filling in all form fields with valid data](https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/163)
[TC_12.001.002 | [Teacher] Create announcement > Create teacher announcement > Verify the announcement is not created when the empty form is submitted](https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/164)
[TC_12.001.003 | [Teacher] Create announcement > Create teacher announcement > Verify the announcement is created after filling in required form fields with valid data](https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/issues/165)
