### ISSUE TITLE
TC_02.001.001.001 | Guest-Header > Sign in(button) > Verify button "Войти" is displayed in the Header

### ISSUE THREAD

**Issue by tgusachenko** [RedRoverSchool/BookClubQA_Python_2024_fall#73]
**Description:**
Header: Verify button "Войти" is displayed/visible

**Preconditions:**
User is not logged in/registered

**Steps:**
1. Open Homepage http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/
2. In Header, locate the button "Войти"

**Expected results:**
Button "Войти" is displayed/visible

**Comment by KatyaMy** [comment]
в пердусловия можно добавить 1 пункт из шагов, и например что пользователь не зарегестрирован

**Comment by ZUmbet** [comment]
Done
