### ISSUE TITLE
TC_00.002.002.001 | Main page (body) - All users > Become a Teacher > Verify button "Стать репетитором" is visible below "Добро пожаловать в "Мыслеплав"!" heading

### ISSUE THREAD

**Issue by tgusachenko** [RedRoverSchool/BookClubQA_Python_2024_fall#77]
**Description:**
Header: Verify button "Стать репетитором" is displayed/visible

**Preconditions:**

**Steps:**

1. Open Homepage http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/
2. In the Header, locate the button "Стать репетитором"

**Expected results:**
Button "Стать репетитором" is displayed/visible

**Comment by usergalina1** [comment]
@tgusachenko, @ZUmbet вопрос.

А почему вы тестируете хедер в description, а не main body(home) page как в заголовке?

На самом деле здесь нужно тестировать кнопку "Стать репетитором" на главной странице, а Вы проверяете кнопку "In the Header, locate the button "Стать репетитором"" (Step 2)

Или надо переименовать тест и тогда нумерация тоже должна быть другой или нужно переписать его совсем

**Comment by ZUmbet** [comment]
> [@tgusachenko](https://github.com/tgusachenko), [@ZUmbet](https://github.com/ZUmbet) вопрос.
> 
> А почему вы тестируете хедер в description, а не main body(home) page как в заголовке?
> 
> На самом деле здесь нужно тестировать кнопку "Стать репетитором" в контейнере "Добро пожаловать в "Мыслеплав"! на главной странице, а Вы проверяете кнопку "In the Header, locate the button "Стать репетитором"" (Step 2)
> 
> Или надо переименовать тест и тогда нумерация тоже должна быть другой или нужно переписать его совсем как мануал шаги, так и автомашин

https://github.com/RedRoverSchool/BookClubQA_Python_2024_fall/pull/169
Fixed. Check please
