### ISSUE TITLE
TC_03.001.007 | Guest > Sign in > Sign in as a registered guest. #17> Profile btn is displayed if User redirected into profile page 

### ISSUE THREAD

**Issue by LilianaKor** [RedRoverSchool/BookClubQA_Python_2024_fall#89]
**Precondition:**
The guest must be registered as either a student or a teacher.
Navigate to the [login page](http://tester:dslfjsdfblkhew%40122b1klbfw@testing.misleplav.ru/login/)

**Test Data:**
Login: Garry
Password: Potter1$

**Steps:**

1. User on http://testing.misleplav.ru/list/ page

2. Observe the Profile button

**ER:**  Profile btn is displayed if User redirected to the profile page from log in page

**Comment by KatyaMy** [comment]
@LilianaKor скинь ссылку на тк под User story.

**Comment by LilianaKor** [comment]
Done. Link on AT is under US
