### ISSUE TITLE
TC_11.003.001.001 | Header - Teacher > Support (Telegram) > Support in Telegram > Visibility of Telegram Support

### ISSUE THREAD

**Issue by arnrtx** [RedRoverSchool/BookClubQA_Python_2024_fall#94]
**Preconditions:**
The teacher is logged in.

**Test Steps:**
1. Go to main page.
2. Check the header menu for the presence of the Support item.

**Expected Result:**
The Support item is visible in the header.

**Comment by KatyaMy** [comment]
Ваш АТ не требуется в логине.
`def test_support_visibility_as_teacher(login, header):
    header.visit()
    header.click_on_login_button()
    login.full_login("teacher_test", "a.9QA{!@HDB;en2")
    header.support_button_should_be_visible()


def test_support_clickability_as_teacher(login, header):
    header.visit()
    header.click_on_login_button()
    login.full_login("teacher_test", "a.9QA{!@HDB;en2")
    header.click_on_support_button()


def test_support_visibility_as_student(login, header):
    header.visit()
    header.click_on_login_button()
    login.full_login("student_test", "]<c%ZTHH8EZ3L–+")
    header.support_button_should_be_visible()`
