### ISSUE TITLE
TC_11.003.001.002 | Header - Teacher > Support (Telegram) > Support in Telegram > Clickability of Telegram Support

### ISSUE THREAD

**Issue by arnrtx** [RedRoverSchool/BookClubQA_Python_2024_fall#95]
**Preconditions:**
The teacher is logged in.

**Test Steps:**
1. Go to main page.
2. Click the Telegram support item in header.

**Expected Result:**

Redirect to https://t.me/misleplav_support_bot/.

**Comment by OxanaSum** [comment]
В ожидаемом результате дублируется шаг 2 из Test steps.
Можно написать, например, так:
"Открывается новая вкладка браузера, ведущая на официальный канал поддержки в Telegram, url = https://t.me/misleplav_support_bot/"
